default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ["-ll"]
        files: .py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies:
          [
            "types-requests",
            "types-freezegun",
            "types-pytz",
            "types-python-dateutil",
            "types-redis",
            "types-mock",
            "types-paramiko",
          ]
        exclude: "migrations/|settings.py"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(js?|ts?|jsx?|tsx?|css|less|sass|scss|md|json|yaml|yml)$
