services:
  web:
    build:
      context: ./releasecab_api
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./releasecab_api:/app/
    ports:
      - 8000:8000
    env_file:
      - ./releasecab_api/environments/env.dev
  ui:
    build:
      context: ./releasecab_ui
      dockerfile: Dockerfile.ui
    command: npm run dev
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./releasecab_ui:/app/
      - node_modules:/app/node_modules
  db:
    image: postgres:15.3-alpine
    env_file:
      - ./releasecab_api/environments/env.dev
volumes:
  node_modules: {}
