# Generated by Django 5.0.2 on 2024-02-23 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('release', '0001_initial'),
        ('tenant', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='affected_teams',
            field=models.ManyToManyField(blank=True, to='user.team'),
        ),
        migrations.AddField(
            model_name='release',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='releasecomment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.release'),
        ),
        migrations.AddField(
            model_name='releasecomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='releasecomment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releaseconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='releaseenvironment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='release',
            name='release_environment',
            field=models.ManyToManyField(blank=True, to='release.releaseenvironment'),
        ),
        migrations.AddField(
            model_name='releasestage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='releaseconfig',
            name='initial_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.releasestage'),
        ),
        migrations.AddField(
            model_name='release',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='release.releasestage'),
        ),
        migrations.AddField(
            model_name='release',
            name='next_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_stages', to='release.releasestage'),
        ),
        migrations.AddField(
            model_name='releasestageconnection',
            name='from_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='release.releasestage'),
        ),
        migrations.AddField(
            model_name='releasestageconnection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='releasestageconnection',
            name='to_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='release.releasestage'),
        ),
        migrations.AddField(
            model_name='releasestageconnectionapprover',
            name='approver_role',
            field=models.ManyToManyField(blank=True, to='user.role'),
        ),
        migrations.AddField(
            model_name='releasestageconnectionapprover',
            name='approver_team',
            field=models.ManyToManyField(blank=True, to='user.team'),
        ),
        migrations.AddField(
            model_name='releasestageconnectionapprover',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='releasestageconnection',
            name='approvers',
            field=models.ManyToManyField(blank=True, to='release.releasestageconnectionapprover'),
        ),
        migrations.AddField(
            model_name='releasetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='release.releasetype'),
        ),
    ]
