# Generated by Django 5.0.2 on 2024-02-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasestage',
            name='allow_release_delete',
            field=models.BooleanField(default=True),
        ),
    ]
