# Generated by Django 5.0.2 on 2024-03-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_releasestage_allow_release_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasestage',
            name='allow_release_update',
            field=models.BooleanField(default=True),
        ),
    ]
