# Generated by Django 5.0.2 on 2024-03-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_releasestage_allow_release_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseenvironment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='releasetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
