# Generated by Django 5.0.2 on 2024-03-07 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_releaseenvironment_is_active_releasetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseconfig',
            name='initial_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='release.releasestage'),
        ),
    ]
