FROM python:3.10.0-alpine3.14

RUN mkdir /app
WORKDIR /app 

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN apk add python3-dev py-pip postgresql-dev
COPY ./requirements.txt /app/
RUN pip install -r /app/requirements.txt
COPY . /app/

RUN chmod 755 /app/entrypoint.dev.sh
ENTRYPOINT ["/app/entrypoint.dev.sh"]
