FROM python:3.10.0-alpine3.14

RUN mkdir /app
WORKDIR /app 

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY . /app/
RUN apk add python3-dev py-pip postgresql-dev
RUN pip install -r /app/releasecab_api/requirements.txt

ENTRYPOINT ["/app/releasecab_api/entrypoint.dev.sh"]
