services:
  vscode:
    image: mcr.microsoft.com/devcontainers/python:3.10
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/releasecab_ui/node_modules
    environment:
      - NODE_ENV=development