name: Backend Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker compose --env-file releasecab_api/environments/env.dev -f docker-compose.dev.yml up -d

      - name: Run tests
        run: |
          docker compose --env-file releasecab_api/environments/env.dev -f docker-compose.dev.yml exec -T web sh -c "PYTHONWARNINGS=ignore coverage run manage.py test"

      - name: Generate coverage report
        run: |
          docker compose --env-file releasecab_api/environments/env.dev -f docker-compose.dev.yml exec -T web sh -c "coverage report"

      - name: Stop and remove Docker container
        run: |
          docker compose --env-file releasecab_api/environments/env.dev -f docker-compose.dev.yml stop
          docker compose --env-file releasecab_api/environments/env.dev -f docker-compose.dev.yml down -v
